### ISSUE TITLE
Family Edition cards

### ISSUE THREAD

**Issue by aeshirey** [JordanPawlett/cards-against-formality-services#29]
Have you considered adding the [CAH Family Edition](https://www.cardsagainsthumanityfamilyedition.com/pdf/CAH_Family_BigCards.pdf) deck to the service? It looks like the B&W cards would only need to be added to [cards.json](https://github.com/JordanPawlett/cards-against-formality-services/blob/7355726bb8d3f667dc2810a018facd81343d550c/services/cards-service/seeds/cards.json) and add a deck type with indexes to those?

If I created a PR, could this be integrated and deployed to the .io website?

**Comment by JordanPawlett** [comment]
Hey! Yep, it'd just be a data ingress task entirely.
I'm happy to populate the data if you can generate it with the correct indicies & B&W cards as you pointed out.

Great idea!
