### ISSUE TITLE
clusterAuth.enabled not disabled for nats helm chart

### ISSUE THREAD

**Issue by bzd2000** [JordanPawlett/cards-against-formality-services#3]
Hello,

I think clusterAuth.enabled should also be set to false in the skaffold.yaml for the nats helm chart
Otherwise the nodes will not able to communicate with the nats.

kr,
Filip

**Comment by bzd2000** [comment]
helm:
    releases:
      - name: nats
        chartPath: bitnami/nats
        remote: true
        setValues: 
          auth.enabled: false
          clusterAuth.enabled: false
      - name: redis
        chartPath: bitnami/redis
        remote: true
        setValues: { usePassword: false }
      - name: mongo
        chartPath: bitnami/mongodb
        remote: true
        setValues: { usePassword: false }

**Comment by JordanPawlett** [comment]
Hi @bzd2000 thank you for your input! 
Could you expand on the problem please? As far I can see everything is connecting to NATS fine in production as is. I can't seem to see any obvious errors.

**Comment by bzd2000** [comment]
Hi,

I was trying to deploy to a kubernetes cluster.
And there was a connection issue with the nats server.  I thought it was because of this setting.
But at the end it was the URI that was wrong .
nats-client.default.svc.cluster.local should be just nats-client in my setup.
Not sure why

**Comment by JordanPawlett** [comment]
Strange, it must be the particular kube cluster you're using!

**Comment by bzd2000** [comment]
i  use microk8s

**Comment by bzd2000** [comment]
anyway, I like the way you structured your services in combination with skaffold :)
